id: IAC51819C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:44:27+00:00'
last_modified: '2022-06-16T05:35:12.444644+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4351
  title: ས་སྐྱ་པའི་བཀའ་སྲུང་རྣམས་ལ་མཆོད་གཏོར་དང་བསྐང་བ་བསྟོད་པ་རྒྱས་པར་བྱ་བའི་རིམ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    81E0:
      image_group_id: I3CN4360
      title: ''
      total_pages: 593
      order: 1
      base_file: 81E0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
